### ISSUE TITLE
ResetVideo failed

### ISSUE THREAD

**Issue by B00B0X** [GoaLitiuM/libobs-sharp#27]
We get an error at ResetVideo with the example 'test' program. Dlls are loaded fine. Version: OBS 21.1.2 (64bit, windows)

```
Unhandled Exception: System.ApplicationException: ResetVideo failed.
   at test.Program.InitObs() in C:\Users\Kaj\Documents\libobs-sharp-master\test\Program.cs:line 79
   at test.Program.Main() in C:\Users\Kaj\Documents\libobs-sharp-master\test\Program.cs:line 39
```

What could be the problem?

**Comment by B00B0X** [comment]
Also at line 260 in va_list.cs, I had to make the following change: 

```
case 's':
case 'S':
```
instead of only

`					case 'S':`

**Comment by EbramTawfik** [comment]
The same for OBS-Studio-0.15.4 x86
Is there any update?

**Comment by mirmilad** [comment]
The same for both x86 (21.0.3) and x64 (20.1.3).
Did you find any solution?

**Comment by GoaLitiuM** [comment]
These bindings have not been maintained for years, and I currently have no interest to keep them up to date, so I'm sorry but you guys have to find another bindings for libobs.
